import type { CustomTheme, ThemeColors } from "../customTheme";
import { DARK_COLORS, EMPTY_BG, LIGHT_COLORS } from "./base";

// Catppuccin family (Mocha + Latte).
const CATPPUCCIN_DARK: ThemeColors = {
  ...DARK_COLORS,
  background: "#1e1e2e",
  foreground: "#cdd6f4",
  card: "#181825",
  cardForeground: "#cdd6f4",
  popover: "#181825",
  popoverForeground: "#cdd6f4",
  button: "#cba6f7",
  buttonForeground: "#1e1e2e",
  secondary: "#313244",
  secondaryForeground: "#cdd6f4",
  muted: "#313244",
  mutedForeground: "#a6adc8",
  accent: "#45475a",
  accentForeground: "#cdd6f4",
  destructive: "#f38ba8",
  border: "#45475a",
  input: "#45475a",
  buttonFace: "#4a4b5a",
  buttonFaceForeground: "#cdd6f4",
  ring: "#cba6f7",
  sidebar: "#11111b",
  sidebarForeground: "#cdd6f4",
  sidebarBorder: "#45475a",
  sidebarAccent: "#585b70",
  sidebarAccentForeground: "#cdd6f4",
  iconWorking: "#f9e2af",
  iconIdle: "#a6e3a1",
  iconBlocked: "#f38ba8",
  iconDone: "#89dceb",
  iconBranch: "#cba6f7",
  diffAdded: "#a6e3a1",
  diffRemoved: "#f38ba8",
  info: "#89dceb",
  resizeHandle: "#45475a",
  // Catppuccin Mocha ANSI 16.
  ansiBlack: "#45475a",
  ansiRed: "#f38ba8",
  ansiGreen: "#a6e3a1",
  ansiYellow: "#f9e2af",
  ansiBlue: "#89b4fa",
  ansiMagenta: "#f5c2e7",
  ansiCyan: "#94e2d5",
  ansiWhite: "#bac2de",
  ansiBrightBlack: "#585b70",
  ansiBrightRed: "#f38ba8",
  ansiBrightGreen: "#a6e3a1",
  ansiBrightYellow: "#f9e2af",
  ansiBrightBlue: "#89b4fa",
  ansiBrightMagenta: "#f5c2e7",
  ansiBrightCyan: "#94e2d5",
  ansiBrightWhite: "#a6adc8",
};
// Catppuccin Latte. Default Latte uses `Text #4c4f69` against `Surface1`/
// `Overlay0` highlights which lands ~3.5:1 - acceptable for body text on
// the page bg, but not for selection text on the highlight bg. Selection
// foregrounds switched to Mocha `Base #1e1e2e` (~9:1) so file-tree picks
// stay readable.
const CATPPUCCIN_LIGHT: ThemeColors = {
  ...LIGHT_COLORS,
  background: "#eff1f5",
  foreground: "#1e1e2e",
  card: "#e6e9ef",
  cardForeground: "#1e1e2e",
  popover: "#e6e9ef",
  popoverForeground: "#1e1e2e",
  button: "#8839ef",
  buttonForeground: "#eff1f5",
  secondary: "#ccd0da",
  secondaryForeground: "#1e1e2e",
  muted: "#ccd0da",
  mutedForeground: "#4c4f69",
  accent: "#bcc0cc",
  accentForeground: "#1e1e2e",
  destructive: "#d20f39",
  border: "#bcc0cc",
  input: "#bcc0cc",
  buttonFace: "#abafb7",
  buttonFaceForeground: "#1e1e2e",
  ring: "#8839ef",
  sidebar: "#e6e9ef",
  sidebarForeground: "#1e1e2e",
  sidebarBorder: "#bcc0cc",
  sidebarAccent: "#acb0be",
  sidebarAccentForeground: "#1e1e2e",
  iconWorking: "#df8e1d",
  iconIdle: "#40a02b",
  iconBlocked: "#d20f39",
  iconDone: "#04a5e5",
  iconBranch: "#8839ef",
  diffAdded: "#40a02b",
  diffRemoved: "#d20f39",
  info: "#04a5e5",
  resizeHandle: "#bcc0cc",
  // Catppuccin Latte ANSI 16 (official light terminal palette).
  ansiBlack: "#5c5f77",
  ansiRed: "#d20f39",
  ansiGreen: "#40a02b",
  ansiYellow: "#df8e1d",
  ansiBlue: "#1e66f5",
  ansiMagenta: "#ea76cb",
  ansiCyan: "#179299",
  ansiWhite: "#acb0be",
  ansiBrightBlack: "#6c6f85",
  ansiBrightRed: "#d20f39",
  ansiBrightGreen: "#40a02b",
  ansiBrightYellow: "#df8e1d",
  ansiBrightBlue: "#1e66f5",
  ansiBrightMagenta: "#ea76cb",
  ansiBrightCyan: "#179299",
  ansiBrightWhite: "#bcc0cc",
};

export const CATPPUCCIN: CustomTheme = {
  name: "Catppuccin",
  light: CATPPUCCIN_LIGHT,
  dark: CATPPUCCIN_DARK,
  background: { ...EMPTY_BG },
};
