import type { CustomTheme, ThemeColors } from "../theme/model";
import { DARK_COLORS, EMPTY_BG, LIGHT_COLORS } from "./base";

// Kanagawa family (Wave dark + Lotus light), after Katsushika Hokusai's
// "The Great Wave off Kanagawa". Muted, painterly palette.
const KANAGAWA_DARK: ThemeColors = {
  ...DARK_COLORS,
  background: "#1f1f28",
  foreground: "#dcd7ba",
  card: "#16161d",
  cardForeground: "#dcd7ba",
  popover: "#16161d",
  popoverForeground: "#dcd7ba",
  button: "#7e9cd8",
  buttonForeground: "#1f1f28",
  secondary: "#2a2a37",
  secondaryForeground: "#dcd7ba",
  muted: "#2a2a37",
  mutedForeground: "#c8c093",
  accent: "#2d4f67",
  accentForeground: "#dcd7ba",
  destructive: "#e82424",
  border: "#363646",
  input: "#363646",
  buttonFace: "#484853",
  buttonFaceForeground: "#dcd7ba",
  ring: "#7e9cd8",
  sidebar: "#16161d",
  sidebarForeground: "#dcd7ba",
  sidebarBorder: "#2a2a37",
  sidebarAccent: "#2d4f67",
  sidebarAccentForeground: "#dcd7ba",
  iconWorking: "#e6c384",
  diffAdded: "#98bb6c",
  info: "#7fb4ca",
  resizeHandle: "#363646",
  // Kanagawa Wave ANSI accents (official terminal palette).
  ansiRed: "#c34043",
  ansiGreen: "#76946a",
  ansiYellow: "#c0a36e",
  ansiBlue: "#7e9cd8",
  ansiMagenta: "#957fb8",
  ansiCyan: "#6a9589",
};
// Kanagawa Lotus (official light variant). Warm parchment surfaces with the
// same muted ink accents; foregrounds kept dark for AA on the cream bg.
const KANAGAWA_LIGHT: ThemeColors = {
  ...LIGHT_COLORS,
  background: "#f2ecbc",
  foreground: "#545464",
  card: "#e5ddb0",
  cardForeground: "#545464",
  popover: "#e5ddb0",
  popoverForeground: "#545464",
  button: "#4d699b",
  buttonForeground: "#f2ecbc",
  secondary: "#dcd5ac",
  secondaryForeground: "#545464",
  muted: "#dcd5ac",
  mutedForeground: "#5a5a4f",
  accent: "#b5cbd2",
  accentForeground: "#1f1f28",
  destructive: "#c84053",
  border: "#d5cea3",
  input: "#d5cea3",
  buttonFace: "#a7a283",
  buttonFaceForeground: "#1f1f28",
  ring: "#4d699b",
  sidebar: "#e5ddb0",
  sidebarForeground: "#545464",
  sidebarBorder: "#d5cea3",
  sidebarAccent: "#b5cbd2",
  sidebarAccentForeground: "#1f1f28",
  iconWorking: "#cc6d00",
  diffAdded: "#6f894e",
  info: "#4d699b",
  resizeHandle: "#d5cea3",
  // Kanagawa Lotus ANSI accents (official light terminal palette).
  ansiRed: "#c84053",
  ansiGreen: "#6f894e",
  ansiYellow: "#77713f",
  ansiBlue: "#4d699b",
  ansiMagenta: "#b35b79",
  ansiCyan: "#597b75",
};

export const KANAGAWA: CustomTheme = {
  name: "Kanagawa",
  light: KANAGAWA_LIGHT,
  dark: KANAGAWA_DARK,
  background: { ...EMPTY_BG },
};
