import type { CustomTheme, ThemeColors } from "../customTheme";
import { DARK_COLORS, EMPTY_BG, LIGHT_COLORS } from "./base";

/**
 * Nebula: near-black cool-grey surfaces with an electric violet accent,
 * periwinkle links and pale cyan chips. Surface ramp goes LIGHTER as the UI
 * gets more chrome-like (canvas darkest, panels above it, floating menus
 * lightest), which is the opposite of the Default preset and what gives this
 * one its layered look. Violet carries every "selected" state, so the accent
 * doubles as the terminal's selection colour.
 */
const NEBULA_DARK: ThemeColors = {
  ...DARK_COLORS,
  background: "#181a1e",
  foreground: "#c3c6cd",
  card: "#1e1f23",
  cardForeground: "#c3c6cd",
  popover: "#23272a",
  popoverForeground: "#e2e5ea",
  button: "#9a10f7",
  buttonForeground: "#ffffff",
  secondary: "#2b2e35",
  secondaryForeground: "#c3c6cd",
  muted: "#212429",
  mutedForeground: "#82858d",
  accent: "#3a1a63",
  accentForeground: "#f3e8ff",
  destructive: "#ff4d6d",
  border: "#2a2e35",
  input: "#333842",
  buttonFace: "#4d4f55",
  buttonFaceForeground: "#c3c6cd",
  ring: "#9a10f7",
  sidebar: "#1a1c20",
  sidebarForeground: "#c3c6cd",
  sidebarBorder: "#2a2e35",
  sidebarAccent: "#3a1a63",
  sidebarAccentForeground: "#f3e8ff",
  iconWorking: "#f0b429",
  iconIdle: "#3ddc97",
  iconBlocked: "#ff4d6d",
  iconDone: "#8caef5",
  iconBranch: "#c07cff",
  diffAdded: "#3ddc97",
  diffRemoved: "#f8809f",
  info: "#7dd3f0",
  tabAccentTerminal: "#3ddc97",
  tabAccentSsh: "#7dd3f0",
  tabAccentEditor: "#9a10f7",
  tabAccentPreview: "#8caef5",
  tabAccentAiDiff: "#e05cff",
  tabAccentGitDiff: "#f0b429",
  resizeHandle: "#2a2e35",
  ansiBlack: "#181a1e",
  ansiRed: "#ff4d6d",
  ansiGreen: "#3ddc97",
  ansiYellow: "#f0b429",
  ansiBlue: "#8caef5",
  ansiMagenta: "#9a10f7",
  ansiCyan: "#7dd3f0",
  ansiWhite: "#c3c6cd",
  ansiBrightBlack: "#4b5058",
  ansiBrightRed: "#ff8098",
  ansiBrightGreen: "#6ef0b8",
  ansiBrightYellow: "#ffd166",
  ansiBrightBlue: "#a9c4ff",
  ansiBrightMagenta: "#c07cff",
  ansiBrightCyan: "#a6e9ff",
  ansiBrightWhite: "#f2f4f8",
};
// Nebula light: the same hues carried onto cool paper. Every accent is
// darkened until it holds up as text on a near-white surface (the dark set's
// neons would smear), and the violet stays the single identity colour.
const NEBULA_LIGHT: ThemeColors = {
  ...LIGHT_COLORS,
  background: "#faf9fc",
  foreground: "#1b1a24",
  card: "#f2f1f7",
  cardForeground: "#1b1a24",
  popover: "#ffffff",
  popoverForeground: "#1b1a24",
  button: "#8b0fe0",
  buttonForeground: "#ffffff",
  secondary: "#eae7f2",
  secondaryForeground: "#1b1a24",
  muted: "#efedf5",
  mutedForeground: "#5b5870",
  accent: "#e7dbff",
  accentForeground: "#2a1348",
  destructive: "#d61f4e",
  border: "#e0dceb",
  input: "#d6d1e4",
  buttonFace: "#b7b4bd",
  buttonFaceForeground: "#1b1a24",
  ring: "#8b0fe0",
  sidebar: "#f2f1f7",
  sidebarForeground: "#1b1a24",
  sidebarBorder: "#e0dceb",
  sidebarAccent: "#e7dbff",
  sidebarAccentForeground: "#2a1348",
  iconWorking: "#a86a06",
  iconIdle: "#0c8560",
  iconBlocked: "#d61f4e",
  iconDone: "#3a63d8",
  iconBranch: "#8b0fe0",
  diffAdded: "#0c8560",
  diffRemoved: "#d61f4e",
  info: "#0b6e93",
  tabAccentTerminal: "#0c8560",
  tabAccentSsh: "#0b6e93",
  tabAccentEditor: "#8b0fe0",
  tabAccentPreview: "#3a63d8",
  tabAccentAiDiff: "#c026d3",
  tabAccentGitDiff: "#a86a06",
  resizeHandle: "#e0dceb",
  ansiBlack: "#2a2833",
  ansiRed: "#d61f4e",
  ansiGreen: "#0c8560",
  ansiYellow: "#a86a06",
  ansiBlue: "#3a63d8",
  ansiMagenta: "#8b0fe0",
  ansiCyan: "#0b6e93",
  ansiWhite: "#e0dceb",
  ansiBrightBlack: "#6b6880",
  ansiBrightRed: "#f0446b",
  ansiBrightGreen: "#12a97a",
  ansiBrightYellow: "#c98a12",
  ansiBrightBlue: "#5b82ef",
  ansiBrightMagenta: "#a341f5",
  ansiBrightCyan: "#1795bd",
  ansiBrightWhite: "#faf9fc",
};

export const NEBULA: CustomTheme = {
  name: "Nebula",
  light: NEBULA_LIGHT,
  dark: NEBULA_DARK,
  background: { ...EMPTY_BG },
};
