import type { CustomTheme, ThemeColors } from "../theme/model";
import { DARK_COLORS, EMPTY_BG, LIGHT_COLORS } from "./base";

// Nord family.
const NORD_DARK: ThemeColors = {
  ...DARK_COLORS,
  background: "#2e3440",
  foreground: "#d8dee9",
  card: "#3b4252",
  cardForeground: "#eceff4",
  popover: "#3b4252",
  popoverForeground: "#eceff4",
  button: "#88c0d0",
  buttonForeground: "#2e3440",
  secondary: "#434c5e",
  secondaryForeground: "#eceff4",
  muted: "#434c5e",
  mutedForeground: "#bdc6d6",
  accent: "#3f577a",
  accentForeground: "#eceff4",
  destructive: "#bf616a",
  border: "#4c566a",
  input: "#4c566a",
  buttonFace: "#616978",
  buttonFaceForeground: "#eceff4",
  ring: "#88c0d0",
  sidebar: "#292e39",
  sidebarForeground: "#d8dee9",
  sidebarBorder: "#4c566a",
  sidebarAccent: "#3f577a",
  sidebarAccentForeground: "#eceff4",
  iconWorking: "#ebcb8b",
  diffAdded: "#a3be8c",
  info: "#81a1c1",
  resizeHandle: "#4c566a",
  // Nord ANSI accents.
  ansiRed: "#bf616a",
  ansiGreen: "#a3be8c",
  ansiYellow: "#ebcb8b",
  ansiBlue: "#81a1c1",
  ansiMagenta: "#b48ead",
  ansiCyan: "#88c0d0",
};
const NORD_LIGHT: ThemeColors = {
  ...LIGHT_COLORS,
  background: "#eceff4",
  foreground: "#2e3440",
  card: "#e5e9f0",
  cardForeground: "#2e3440",
  popover: "#e5e9f0",
  popoverForeground: "#2e3440",
  button: "#3f577a",
  buttonForeground: "#eceff4",
  secondary: "#d8dee9",
  secondaryForeground: "#2e3440",
  muted: "#d8dee9",
  mutedForeground: "#4c566a",
  accent: "#88c0d0",
  accentForeground: "#2e3440",
  destructive: "#bf616a",
  border: "#d8dee9",
  input: "#d8dee9",
  buttonFace: "#a8adb6",
  buttonFaceForeground: "#2e3440",
  ring: "#5e81ac",
  sidebar: "#e5e9f0",
  sidebarForeground: "#2e3440",
  sidebarBorder: "#d8dee9",
  sidebarAccent: "#88c0d0",
  sidebarAccentForeground: "#2e3440",
  iconWorking: "#d08770",
  diffAdded: "#a3be8c",
  info: "#5e81ac",
  resizeHandle: "#d8dee9",
  // Nord has no official light terminal palette; the standard Nord ANSI is
  // tuned for dark surfaces (green/yellow/cyan wash out on #eceff4). These are
  // the same Nord hues deepened to read on the light background while keeping
  // the Frost/Aurora character.
  ansiRed: "#99313b",
  ansiGreen: "#4f6a43",
  ansiYellow: "#9a7227",
  ansiBlue: "#5e81ac",
  ansiMagenta: "#8a5d80",
  ansiCyan: "#3b7e8e",
};

export const NORD: CustomTheme = {
  name: "Nord",
  light: NORD_LIGHT,
  dark: NORD_DARK,
  background: { ...EMPTY_BG },
};
